openapi: '3.0.3'
info:
  title: SMA Document API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /documents:
    get:
      tags:
        - documents
      summary: Returns list of all active documents
      operationId: documentsList
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'          
components:
  schemas:
    Document:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 13
        header:
          type: string
          example: Document 1
        description:
          type: string
          example: This is the first document
        lastModified:
          type: string
          format: date-time
          example: 2024-07-03T10:43:21Z
        created:
          type: string
          format: date-time
          example: 2024-07-03T10:43:21Z
